# let Quizzes generated by AI, and get Quizes from API of deepseek

from .quiz import Quiz, QuizRequest


class QuizLoaderAI:
    def __init__(self):
        ...

    def dump_and_drop_quizzes(self, file_path: str):
        ...

    def get_quizzes(self, quiz_request: QuizRequest) -> list[Quiz]:
        ...
