# let Quizzes generated by AI, and get Quizes from API of deepseek

import json
import os

from openai import OpenAI

from .prompt import system_prompt, user_prompt
from .quiz import Quiz, QuizRequest
from .quizLoader import readBlock

# At import time:

# Load API key and URL from JSON file
with open("config.json") as f:
    config = json.load(f)

# Fallback to the actual API key if the placeholder is not replaced
# This is for security reasons, avoiding hardcoding the API key in the codebase
if config["api_key"] == "<YOUR_API_KEY_HERE>":
    with open("config_me.json") as f:
        config = json.load(f)

try:
    BASE_URL = config["base_URL"]
    MODEL = config["model"]
    API_KEY = config["api_key"]
except KeyError as e:
    print(f"Missing key in config: {e}")
    raise

if MODEL == "default":
    MODEL = "deepseek-v4-pro"


class QuizLoaderAI:
    def __init__(self):
        self.client = OpenAI(
            api_key=API_KEY,
            base_url=BASE_URL,
        )
        self.quiz_id: int = 0
        self.last_category: str = ""
        self.loaded_quizzes: list[Quiz] = []

    def dump_and_drop_quizzes(self, file_path: str)->str:
        if file_path.lower().endswith(".json"):
            filename = file_path[:-5]
        else:
            filename = file_path

        retry: int = 0
        file_path_retry = f"{filename}.json"
        while os.path.exists(file_path_retry):
            if retry >= 99:
                raise RuntimeError("Too many question files with the same name.")
            retry += 1
            file_path_retry = f"{filename}_{retry:04d}.json"

        file_path_actual = file_path_retry
        try:
            with open(file_path_actual, "w", encoding="utf-8") as f:
                json.dump(
                    {
                        "collection_name": f"{filename}",
                        "description": "Quizzes Generated by AI",
                        "category": self.last_category,
                        "quizzes": [quiz.to_dict() for quiz in self.loaded_quizzes],
                    },
                    f,
                    ensure_ascii=False,
                    indent=4,
                )
            self.loaded_quizzes.clear()
        except Exception as e:
            print(f"Failed to dump quizzes to file: {e}")
            print([quiz.to_dict() for quiz in self.loaded_quizzes])
            try:
                os.remove(file_path_actual)
            except Exception as e:
                pass
        return file_path_actual

    def parse_response(self, response_content) -> list[Quiz]:
        try:
            quizzes_data = json.loads(response_content)
            quizzes = []
            for quiz_data in quizzes_data.get("quizzes", []):
                self.quiz_id += 1
                quiz = Quiz(
                    id=str(f"{self.quiz_id:04d}"),  # Generate a unique ID for each quiz
                    type=quiz_data.get("type", ""),
                    content_blocks=readBlock(quiz_data),
                    options=quiz_data.get("options", []),
                    answer=quiz_data.get("answer", ""),
                    category=quiz_data.get("category", ""),
                )
                quizzes.append(quiz)
            else:
                print(f"Loaded {len(quizzes)} quizzes from response.")
            return quizzes
        except json.JSONDecodeError as e:
            print(f"Failed to parse JSON response: {e}")
            return []

    def get_quizzes(self, quiz_request: QuizRequest) -> list[Quiz]:
        user_prompt_formatted = user_prompt.format(
            count=quiz_request.count,
            category=quiz_request.category,
            topic=quiz_request.topic,
            difficulty=quiz_request.difficulty,
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt_formatted},
        ]

        response = self.client.chat.completions.create(
            model=MODEL, messages=messages, response_format={"type": "json_object"}
        )

        """
        Example Return JSON of `response.choices[0].message.content`:
        ```json
            {
                "quizzes": [
                    {
                        "type": "short_answer",
                        "question": "...",
                        "answer": "...",
                        "category": "..."
                    }
                ]
            }
        ```
        """

        quizzes = self.parse_response(response.choices[0].message.content)
        self.last_category = quiz_request.category
        self.loaded_quizzes.extend(quizzes)

        return quizzes


if __name__ == "__main__":
    pass
